from scapy.all import *
from network import *

sched=scheduler(tick=0.001,finish=5)

host1=host('host1',stack='udp') # Good traffic generator
host2=host('host2',stack='udp',mdrop='00:00:00:00:00:00') # terminal, dropping fake traffic
host3=host('host3',stack='udp',mdst='00:00:00:00:00:00') # fake traffic generator

smallbuffers=8000
standardbuffers=64000

traf=trafgen('traf1',ms1=1)
# traf=trafgen('traf1')
term2=terminal('term2')
#flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=1)

scenario=4

if scenario == 0:
   flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=10)
   sw=datalink('pon',capacity=10)
#   sw=eth_switch('pon')
#   sw=datalink('node1',latency=40)
   connect('hostcon1',host1.B,traf.B)
   connect('con1',host1.A,sw.B)
   connect('con2',sw.A,host2.A)
   connect('hostcon2',host2.B,term2.A)
   connect('flow',flowgen.B, host3.B)
   connect('con3',host3.A, sw.B)
elif scenario == 1: # Classic architecture - base
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=10,fblimit=5)
  on=datalink('pon',latency=10)
  onu=vswitch('onu',"","Dot1Q(vlan=22)")
  olt=vswitch('olt',"Dot1Q(vlan=22)","")
  cpe=vswitch('cpe',"","Dot1Q(vlan=35)")
  bras=vswitch('bras',"Dot1Q(vlan=35)","")
  homerouter=eth_switch('hr')
  metrorouter=vswitch('mr',"","MPLS(label=250)")
  corerouter=vswitch('cr',"MPLS(label=250)","")
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  connect('c1',homerouter.B,cpe.A)
  connect('c2',cpe.B,onu.A)
  connect('c3',onu.B,pon.A)
  connect('c4',pon.B,olt.A)
  connect('c5',olt.B,bras.A)
  connect('c6',bras.B,metrorouter.A)
  connect('c7',metrorouter.B,corerouter.A)
  connect('c8',host2.A,homerouter.A)
  connect('c9',host1.A,corerouter.B)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, corerouter.B)
elif scenario == 2: # Classic architecture - standard buffers 
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=5)
  pon=datalink('pon',latency=2,capacity=10,ber=-12,MaxSize=standardbuffers)
  link1=datalink('link1',latency=2,ber=-12,MaxSize=standardbuffers)
  link2=datalink('link2',latency=2,ber=-12,capacity=5,MaxSize=standardbuffers)
  link3=datalink('link3',latency=2,ber=-12,MaxSize=standardbuffers)
  onu=vswitch('onu',"","Dot1Q(vlan=22)",MaxSize=standardbuffers)
  olt=vswitch('olt',"Dot1Q(vlan=22)","",MaxSize=standardbuffers)
  cpe=vswitch('cpe',"","Dot1Q(vlan=35)",MaxSize=standardbuffers)
  bras=vswitch('bras',"Dot1Q(vlan=35)","",MaxSize=standardbuffers)
  homerouter=eth_switch('hr',MaxSize=standardbuffers)
  metrorouter=vswitch('mr',"","MPLS(label=250)",MaxSize=standardbuffers)
  corerouter=vswitch('cr',"MPLS(label=250)","",MaxSize=standardbuffers)
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  connect('c1',homerouter.B,cpe.A)
  connect('c2',cpe.B,onu.A)
  connect('c3',onu.B,pon.A)
  connect('c4',pon.B,olt.A)
  connect('c5',olt.B,bras.A)
  connect('c6',bras.B,link1.A)
  connect('c7',link1.B,metrorouter.A)
  connect('c8',metrorouter.B,link2.A)
  connect('c9',link2.B,corerouter.A)
  connect('c10',corerouter.B,link3.A)
  connect('c8',host2.A,homerouter.A)
  connect('c9',host1.A,link3.B)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, corerouter.B)
elif scenario == 3: # Classic architecture - standard buffers, Aged Queue (to deal with buffer bloat)
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=5)
  pon=datalink('pon',latency=2,capacity=10,ber=-12,MaxSize=standardbuffers)
  link1=datalink('link1',latency=2,ber=-12,MaxSize=standardbuffers)
  link2=datalink('link2',latency=2,ber=-12,capacity=5,MaxSize=standardbuffers)
  link3=datalink('link3',latency=2,ber=-12,MaxSize=standardbuffers)
  onu=vswitch('onu',"","Dot1Q(vlan=22)",MaxSize=standardbuffers)
  olt=vswitch('olt',"Dot1Q(vlan=22)","",MaxSize=standardbuffers)
  cpe=vswitch('cpe',"","Dot1Q(vlan=35)",MaxSize=standardbuffers)
  bras=vswitch('bras',"Dot1Q(vlan=35)","",MaxSize=standardbuffers)
  homerouter=eth_switch('hr',MaxSize=standardbuffers)
  metrorouter=vswitch('mr',"","MPLS(label=250)",MaxSize=standardbuffers,age=10)
  corerouter=vswitch('cr',"MPLS(label=250)","",MaxSize=standardbuffers,age=10)
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  connect('c1',homerouter.B,cpe.A)
  connect('c2',cpe.B,onu.A)
  connect('c3',onu.B,pon.A)
  connect('c4',pon.B,olt.A)
  connect('c5',olt.B,bras.A)
  connect('c6',bras.B,link1.A)
  connect('c7',link1.B,metrorouter.A)
  connect('c8',metrorouter.B,link2.A)
  connect('c9',link2.B,corerouter.A)
  connect('c10',corerouter.B,link3.A)
  connect('c8',host2.A,homerouter.A)
  connect('c9',host1.A,link3.B)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, corerouter.B)
elif scenario == 4: # New Arch - standard buffers
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=5)
  pon=datalink('pon',latency=2,ber=-12,capacity=10,MaxSize=standardbuffers)
  link1=datalink('link1',latency=2,ber=-12,MaxSize=standardbuffers)
  link2=datalink('link2',latency=2,ber=-12,MaxSize=standardbuffers)
  link3=datalink('link3',latency=2,ber=-12,MaxSize=standardbuffers,capacity=5)
  onu=vswitch('onu',"","Dot1Q(vlan=70)",MaxSize=standardbuffers)
  olt=vswitch('olt',"Dot1Q(vlan=70)","",MaxSize=standardbuffers)
  cpe=eth_switch('cpe',MaxSize=standardbuffers)
  accessswitch=eth_switch('as',MaxSize=standardbuffers)
  metroswitch=eth_switch('ms',MaxSize=standardbuffers)
  coreswitch=eth_switch('cs')
  connect('c1',cpe.B,onu.A)
  connect('c2',onu.B,pon.A)
  connect('c3',pon.B,olt.A)
  connect('c4',olt.B,link1.A)
  connect('c5',link1.B,accessswitch.A)
  connect('c6',accessswitch.B,link2.A)
  connect('c7',link2.B,metroswitch.A)
  connect('c8',metroswitch.B,link3.A)
  connect('c9',link3.B,coreswitch.A)
  connect('c10',host1.A,coreswitch.B)
  connect('c11',host2.A,cpe.A)
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, coreswitch.B)
elif scenario == 5: #New Arch - small buffers
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=5)
  pon=datalink('pon',latency=2,ber=-12,capacity=10,MaxSize=smallbuffers)
  link1=datalink('link1',latency=2,ber=-12,MaxSize=smallbuffers)
  link2=datalink('link2',latency=2,ber=-12,MaxSize=smallbuffers)
  link3=datalink('link3',latency=2,ber=-12,MaxSize=smallbuffers,capacity=5)
  onu=vswitch('onu',"","Dot1Q(vlan=70)",MaxSize=smallbuffers)
  olt=vswitch('olt',"Dot1Q(vlan=70)","",MaxSize=smallbuffers)
  cpe=eth_switch('cpe',MaxSize=smallbuffers)
  accessswitch=eth_switch('as',MaxSize=smallbuffers)
  metroswitch=eth_switch('ms',MaxSize=smallbuffers)
  coreswitch=eth_switch('cs')
  connect('c1',cpe.B,onu.A)
  connect('c2',onu.B,pon.A)
  connect('c3',pon.B,olt.A)
  connect('c4',olt.B,link1.A)
  connect('c5',link1.B,accessswitch.A)
  connect('c6',accessswitch.B,link2.A)
  connect('c7',link2.B,metroswitch.A)
  connect('c8',metroswitch.B,link3.A)
  connect('c9',link3.B,coreswitch.A)
  connect('c10',host1.A,coreswitch.B)
  connect('c11',host2.A,cpe.A)
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, coreswitch.B)
elif scenario == 6: # New Arch - small buffers and flow control
  flowgen=flowgen('flowgen',start=0.002,stop=1.0,ival=0.05,flowcount=5,fblimit=3)
  pon=datalink('pon',latency=2,ber=-12,capacity=10,MaxSize=smallbuffers)
  link1=datalink('link1',latency=2,ber=-12,MaxSize=smallbuffers)
  link2=datalink('link2',latency=2,ber=-12,MaxSize=smallbuffers)
  link3=datalink('link3',latency=2,ber=-12,MaxSize=smallbuffers,capacity=5)
  onu=vswitch('onu',"","Dot1Q(vlan=70)",MaxSize=smallbuffers)
  olt=vswitch('olt',"Dot1Q(vlan=70)","",MaxSize=smallbuffers)
  cpe=eth_switch('cpe',MaxSize=smallbuffers)
  accessswitch=eth_switch('as',MaxSize=smallbuffers)
  metroswitch=eth_switch('ms',MaxSize=smallbuffers)
  coreswitch=eth_switch('cs')
  connect('c1',cpe.B,onu.A)
  connect('c2',onu.B,pon.A)
  connect('c3',pon.B,olt.A)
  connect('c4',olt.B,link1.A)
  connect('c5',link1.B,accessswitch.A)
  connect('c6',accessswitch.B,link2.A)
  connect('c7',link2.B,metroswitch.A)
  connect('c8',metroswitch.B,link3.A)
  connect('c9',link3.B,coreswitch.A)
  connect('c10',host1.A,coreswitch.B)
  connect('c11',host2.A,cpe.A)
  connect('hostcon1',host1.B,traf.B)
  connect('hostcon2',host2.B,term2.A)
  #
  connect('flow',flowgen.B, host3.B)
  connect('con3',host3.A, coreswitch.B)


sched.process()

